apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkpoint-storage
  namespace: ray-training
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      type: nfs-checkpoint
  storageClassName: ""
