apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-checkpoint
  labels:
    type: nfs-checkpoint
    storage-tier: shared
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10
    path: /mnt/nfs/share
